In [1]:
# Import required libraries
import pandas as pd
import numpy as np

In [2]:
# Load datasets
books = pd.read_csv('../data/Books.csv')
users = pd.read_csv('../data/Users.csv')
ratings = pd.read_csv('../data/Ratings.csv')
# Remove implicit ratings (0)
ratings = ratings[ratings['Book-Rating'] != 0]

C:\Users\nimya\AppData\Local\Temp\ipykernel_9056\530307758.py:2: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('../data/Books.csv')

In [3]:
# Display column names
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='str')

In [4]:
# Inspect dataset dimensions
print("Books:", books.shape)
print("Users:", users.shape)
print("Ratings:", ratings.shape)

Books: (271360, 8)
Users: (278858, 3)
Ratings: (433671, 3)

In [5]:
# Display the first rows of each dataset
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [6]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [7]:
ratings.head()

   User-ID        ISBN  Book-Rating
1   276726  0155061224            5
3   276729  052165615X            3
4   276729  0521795028            6
6   276736  3257224281            8
7   276737  0600570967            6

In [8]:
# check missing values
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [9]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [10]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [11]:
# check duplicates
books.duplicated().sum()

np.int64(0)

In [12]:
users.duplicated().sum()

np.int64(0)

In [13]:
ratings.duplicated().sum()

np.int64(0)

# Top 50 popular Books

In [14]:
# Combine ratings with book metadata (title/author/image)
ratings_with_name = ratings.merge(books,on='ISBN')

In [15]:
# Count how many ratings each book received
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            1
1        Ask Lily (Young Women of Faith: Lily Series, ...            1
2                                            Dark Justice            1
3        Earth Prayers From around the World: 365 Pray...            7
4        Final Fantasy Anthology: Official Strategy Gu...            2
...                                                   ...          ...
135562  Ã?Â?bernachten mit Stil. Die schÃ?Â¶nsten Coun...            1
135563                     Ã?Â?rger mit Produkt X. Roman.            3
135564                                Ã?Â?sterlich leben.            1
135565                              Ã?Â?stlich der Berge.            1
135566                                  Ã?Â?thique en toc            1

[135567 rows x 2 columns]

In [16]:
# Compute average rating per book
avg_rating_df = ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'},inplace=True)
avg_rating_df

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    9.000000
1        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
2                                            Dark Justice   10.000000
3        Earth Prayers From around the World: 365 Pray...    7.142857
4        Final Fantasy Anthology: Official Strategy Gu...   10.000000
...                                                   ...         ...
135562  Ã?Â?bernachten mit Stil. Die schÃ?Â¶nsten Coun...    8.000000
135563                     Ã?Â?rger mit Produkt X. Roman.    7.000000
135564                                Ã?Â?sterlich leben.    7.000000
135565                              Ã?Â?stlich der Berge.    8.000000
135566                                  Ã?Â?thique en toc    8.000000

[135567 rows x 2 columns]

In [17]:
# Merge count + average into one table
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,1,9.000000
1,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
2,Dark Justice,1,10.000000
3,Earth Prayers From around the World: 365 Pray...,7,7.142857
4,Final Fantasy Anthology: Official Strategy Gu...,2,10.000000
...,...,...,...
135562,Ã?Â?bernachten mit Stil. Die schÃ?Â¶nsten Coun...,1,8.000000
135563,Ã?Â?rger mit Produkt X. Roman.,3,7.000000
135564,Ã?Â?sterlich leben.,1,7.000000
135565,Ã?Â?stlich der Berge.,1,8.000000
135566,Ã?Â?thique en toc,1,8.000000

In [18]:
# Keep only books with many ratings and take top 50
popular_df = popular_df[popular_df['num_ratings']>=100].sort_values('avg_rating',ascending=False).head(50)
popular_df

,Book-Title,num_ratings,avg_rating
119061,"The Two Towers (The Lord of the Rings, Part 2)",136,9.330882
115128,"The Return of the King (The Lord of the Rings,...",103,9.213592
45381,Harry Potter and the Goblet of Fire (Book 4),247,9.125506
45400,Harry Potter and the Sorcerer's Stone (Book 1),176,9.062500
45385,Harry Potter and the Order of the Phoenix (Boo...,211,9.047393
45393,Harry Potter and the Prisoner of Azkaban (Book 3),277,9.043321
123681,To Kill a Mockingbird,267,8.977528
45403,Harry Potter and the Sorcerer's Stone (Harry P...,315,8.936508
34428,Ender's Game (Ender Wiggins Saga (Paperback)),151,8.920530
104949,The Fellowship of the Ring (The Lord of the Ri...,205,8.882927
45374,Harry Potter and the Chamber of Secrets (Book 2),326,8.840491
441,1984,144,8.784722
107397,The Hobbit : The Enchanting Prelude to The Lor...,161,8.739130
117778,"The Subtle Knife (His Dark Materials, Book 2)",107,8.672897
106039,The Giver (21st Century Reference),102,8.627451
3283,A Prayer for Owen Meany,182,8.615385
129610,Watership Down,134,8.611940
125564,"Tuesdays with Morrie: An Old Man, a Young Man,...",250,8.588000
101587,The Color Purple,145,8.586207
36288,Fahrenheit 451,204,8.549020
40128,Fried Green Tomatoes at the Whistle Stop Cafe,126,8.531746
107378,The Hitchhiker's Guide to the Galaxy,136,8.529412
106651,The Green Mile,114,8.526316
72599,Night,100,8.520000
76293,Outlander,139,8.496403
116196,The Secret Life of Bees,406,8.477833
87250,Seabiscuit: An American Legend,133,8.473684
106893,The Handmaid's Tale,125,8.456000
102703,The Da Vinci Code,494,8.439271
36894,Fast Food Nation: The Dark Side of the All-Ame...,154,8.415584
106189,"The Golden Compass (His Dark Materials, Book 1)",160,8.400000
89601,Silence of the Lambs,121,8.380165
4837,ANGELA'S ASHES,136,8.360294
113906,The Poisonwood Bible,112,8.348214
8261,Animal Farm,120,8.300000
45188,Hard Eight : A Stephanie Plum Novel (A Stephan...,124,8.298387
98676,The Bean Trees,192,8.281250
49766,I Know This Much Is True,106,8.264151
125998,Two for the Dough,112,8.258929
72564,Nickel and Dimed: On (Not) Getting By in America,174,8.258621
101603,The Color of Water: A Black Man's Tribute to H...,111,8.252252
4260,A Walk in the Woods: Rediscovering America on ...,106,8.207547
63384,Lucky : A Memoir,133,8.195489
110229,The Lovely Bones: A Novel,707,8.185290
114960,The Red Tent (Bestselling Backlist),383,8.182768
39577,Four Blind Mice,104,8.182692
97674,The Alchemist: A Fable About Following Your Dream,126,8.182540
113907,The Poisonwood Bible: A Novel,218,8.178899
80707,Prodigal Summer: A Novel,138,8.159420
108493,The Joy Luck Club,208,8.153846

In [19]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-L','num_ratings','avg_rating']]
popular_df

,Book-Title,Book-Author,Image-URL-L,num_ratings,avg_rating
0,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,136,9.330882
11,"The Return of the King (The Lord of the Rings,...",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339738.0...,103,9.213592
21,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,247,9.125506
23,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,176,9.062500
27,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,211,9.047393
31,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,277,9.043321
34,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,267,8.977528
42,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,315,8.936508
44,Ender's Game (Ender Wiggins Saga (Paperback)),Orson Scott Card,http://images.amazon.com/images/P/0312853238.0...,151,8.920530
48,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,205,8.882927
57,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,326,8.840491
60,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,144,8.784722
69,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,161,8.739130
70,"The Subtle Knife (His Dark Materials, Book 2)",PHILIP PULLMAN,http://images.amazon.com/images/P/0375823468.0...,107,8.672897
78,The Giver (21st Century Reference),LOIS LOWRY,http://images.amazon.com/images/P/0440219078.0...,102,8.627451
80,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,182,8.615385
82,Watership Down,Richard George Adams,http://images.amazon.com/images/P/038039586X.0...,134,8.611940
86,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,250,8.588000
89,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,145,8.586207
95,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,204,8.549020
108,Fried Green Tomatoes at the Whistle Stop Cafe,Fannie Flagg,http://images.amazon.com/images/P/0070212570.0...,126,8.531746
112,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,136,8.529412
121,The Green Mile,Stephen King,http://images.amazon.com/images/P/0671032658.0...,114,8.526316
124,Night,Elie Wiesel,http://images.amazon.com/images/P/0553272535.0...,100,8.520000
129,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,139,8.496403
135,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,406,8.477833
141,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,133,8.473684
143,The Handmaid's Tale,Margaret Atwood,http://images.amazon.com/images/P/0449212602.0...,125,8.456000
147,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,494,8.439271
153,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,154,8.415584
154,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,160,8.400000
162,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,121,8.380165
165,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,136,8.360294
167,The Poisonwood Bible,Barbara Kingsolver,http://images.amazon.com/images/P/0060175400.0...,112,8.348214
170,Animal Farm,George Orwell,http://images.amazon.com/images/P/0451526341.0...,120,8.300000
180,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,124,8.298387
185,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,192,8.281250
188,I Know This Much Is True,Wally Lamb,http://images.amazon.com/images/P/0060987561.0...,106,8.264151
192,Two for the Dough,Janet Evanovich,http://images.amazon.com/images/P/0671001795.0...,112,8.258929
193,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,174,8.258621
195,The Color of Water: A Black Man's Tribute to H...,James McBride,http://images.amazon.com/images/P/1573225789.0...,111,8.252252
197,A Walk in the Woods: Rediscovering America on ...,Bill Bryson,http://images.amazon.com/images/P/0767902521.0...,106,8.207547
198,Lucky : A Memoir,Alice Sebold,http://images.amazon.com/images/P/0316096199.0...,133,8.195489
199,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,707,8.185290
200,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,383,8.182768
201,Four Blind Mice,James Patterson,http://images.amazon.com/images/P/0316693006.0...,104,8.182692
205,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,126,8.182540
207,The Poisonwood Bible: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060930535.0...,218,8.178899
208,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,138,8.159420
209,The Joy Luck Club,Amy Tan,http://images.amazon.com/images/P/0804106304.0...,208,8.153846

# Collaborative filtering based recommender system

In [20]:
# Keep only "active users" (users who rated many books)
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 20
active_users = x[x].index

In [21]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(active_users)]

In [22]:
# Keep only "popular books" (books with enough ratings)
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=10
famous_books = y[y].index
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [23]:
# Pivot table: rows = books, columns = users, values = ratings
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')
pt.fillna(0,inplace=True)
pt

User-ID,242,254,507,638,643,651,709,805,882,929,...,277965,278026,278137,278188,278202,278221,278356,278418,278582,278633
Book-Title,,,,,,,,,,,,,,,,,,,,,
'Salem's Lot,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 Lb. Penalty,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101 Dalmatians,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"14,000 Things to Be Happy About",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Lighthouse Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\Surely You're Joking, Mr. Feynman!\"": Adventures of a Curious Character""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
e,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
stardust,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
# Compute cosine similarity between all book vectors (706x706)
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
similarity_scores = cosine_similarity(pt)

In [26]:
similarity_scores.shape

(2766, 2766)

In [27]:
# Return a list of similar books based on cosine similarity
def recommend(book_name):
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:5]

    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-L'].values))

        data.append(item)

    return data

In [28]:
recommend('Year of Wonders')

[['Where or When  : A Novel',
  'Anita Shreve',
  'http://images.amazon.com/images/P/0156006529.01.LZZZZZZZ.jpg'],
 ["FROM POTTER'S FIELD",
  'Patricia Cornwell',
  'http://images.amazon.com/images/P/0684195984.01.LZZZZZZZ.jpg'],
 ['Peace Like a River',
  'Leif Enger',
  'http://images.amazon.com/images/P/0802139256.01.LZZZZZZZ.jpg'],
 ['Memoirs of a Geisha Uk',
  'Arthur Golden',
  'http://images.amazon.com/images/P/0099771519.01.LZZZZZZZ.jpg']]

In [29]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [30]:
books.drop_duplicates('Book-Title')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271354,0449906736,Flashpoints: Promise and Peril in a New World,Robin Wright,1993,Ballantine Books,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [31]:
# Save models for Flask app (Pickle files)
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))

In [32]:
# Move saved model files into the models folder
import os
import shutil

for file in ['popular.pkl', 'pt.pkl', 'books.pkl', 'similarity_scores.pkl']:
    shutil.move(file, f'../models/{file}')

In [33]:
# Check saved model files
os.listdir('../models')

['books.pkl', 'popular.pkl', 'pt.pkl', 'similarity_scores.pkl']